[build-system]
requires = ["flit"]
build-backend = "flit.buildapi"

[tool.flit.metadata]
module = "streamcables"
author = "Sander van Dragt"
author-email = "sander@vandragt.com"
home-page = "https://vandragt.com/streamcables"
classifiers = ["License :: OSI Approved :: MIT License"]

